# Generated by Django 5.0.2 on 2024-09-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
