# Generated by Django 5.0.2 on 2024-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loggedinuser_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='session_key',
        ),
        migrations.AddField(
            model_name='loggedinuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
